version: '3.8'

services:
  php:
    build:
      context: .
    container_name: php_app
    volumes:
      - .:/var/www/html
    expose:
      - "9000"
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    container_name: nginx_web
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - webnet

networks:
  webnet: